### ISSUE TITLE
Error: uninitialized constant Cask::CaskLoader::FromTapPathLoader

### ISSUE THREAD

**Issue by FanxJK** [jysperm/homebrew-leftover-scanner#9]
```
➜  ~ brew scan-leftovers
Error: uninitialized constant Cask::CaskLoader::FromTapPathLoader
Did you mean?  Cask::CaskLoader::FromTapLoader
               Cask::CaskLoader::FromPathLoader
               Cask::CaskLoader::FromAPILoader
/opt/homebrew/Library/Taps/jysperm/homebrew-leftover-scanner/cmd/brew-scan-leftovers.rb:22:in `block in get_all_casks'
/opt/homebrew/Library/Taps/jysperm/homebrew-leftover-scanner/cmd/brew-scan-leftovers.rb:21:in `map'
/opt/homebrew/Library/Taps/jysperm/homebrew-leftover-scanner/cmd/brew-scan-leftovers.rb:21:in `get_all_casks'
/opt/homebrew/Library/Taps/jysperm/homebrew-leftover-scanner/cmd/brew-scan-leftovers.rb:79:in `<top (required)>'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:10:in `require'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:10:in `require?'
/opt/homebrew/Library/Homebrew/brew.rb:88:in `<main>'
```

**Comment by SteveShi** [comment]
I have this issus too.

**Comment by mcwq123** [comment]
I have the same issus, too

wq@WQMacPro ~ % brew scan-leftovers
Error: uninitialized constant Cask::CaskLoader::FromTapPathLoader
Did you mean?  Cask::CaskLoader::FromTapLoader
               Cask::CaskLoader::FromPathLoader
               Cask::CaskLoader::FromAPILoader
/opt/homebrew/Library/Taps/jysperm/homebrew-leftover-scanner/cmd/brew-scan-leftovers.rb:22:in `block in get_all_casks'
/opt/homebrew/Library/Taps/jysperm/homebrew-leftover-scanner/cmd/brew-scan-leftovers.rb:21:in `map'
/opt/homebrew/Library/Taps/jysperm/homebrew-leftover-scanner/cmd/brew-scan-leftovers.rb:21:in `get_all_casks'
/opt/homebrew/Library/Taps/jysperm/homebrew-leftover-scanner/cmd/brew-scan-leftovers.rb:79:in `<top (required)>'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:10:in `require'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:10:in `require?'
/opt/homebrew/Library/Homebrew/brew.rb:97:in `<main>'
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/jysperm/homebrew-leftover-scanner/issues/new
